import { Octokit } from "@octokit/rest";
import { z } from "zod";
import { getEnv } from "@/server/config/env";
import { createChildLogger } from "@/server/config/logger";
import { withRetry } from "@/server/lib/retry";

const logger = createChildLogger({ module: "pr-service" });

// ─── Types ──────────────────────────────────────────────────────────────────

export const PRRequestSchema = z.object({
  ticketRef: z.string().min(1),
  branch: z.string().min(1),
  title: z.string().min(1),
  body: z.string().min(1),
  labels: z.array(z.string()).default([]),
});
export type PRRequest = z.infer<typeof PRRequestSchema>;

export const PRResultSchema = z.object({
  prNumber: z.number().int().positive(),
  prUrl: z.string().url(),
  branch: z.string(),
});
export type PRResult = z.infer<typeof PRResultSchema>;

// ─── PR Creation ────────────────────────────────────────────────────────────

/**
 * Create a GitHub pull request via Octokit.
 * Requires GITHUB_TOKEN and GITHUB_REPO env vars.
 * Includes retry logic for transient GitHub API failures.
 */
export async function createPullRequest(
  request: PRRequest,
  signal?: AbortSignal
): Promise<PRResult> {
  const env = getEnv();

  if (!env.GITHUB_TOKEN || !env.GITHUB_REPO) {
    throw new Error(
      "GITHUB_TOKEN and GITHUB_REPO must be configured for PR creation"
    );
  }

  const [owner, repo] = env.GITHUB_REPO.split("/");
  if (!owner || !repo) {
    throw new Error(
      'GITHUB_REPO must be in "owner/repo" format'
    );
  }

  const octokit = new Octokit({ auth: env.GITHUB_TOKEN });

  const pr = await withRetry(
    async () => {
      signal?.throwIfAborted();
      const { data } = await octokit.pulls.create({
        owner,
        repo,
        title: `fix: ${request.title} [${request.ticketRef}]`,
        body: request.body,
        head: request.branch,
        base: "main",
      });
      return data;
    },
    { maxAttempts: 3, baseDelayMs: 1000, signal }
  );

  // Add labels if provided
  if (request.labels.length > 0) {
    await octokit.issues.addLabels({
      owner,
      repo,
      issue_number: pr.number,
      labels: request.labels,
    });
  }

  logger.info(
    { prNumber: pr.number, ticketRef: request.ticketRef },
    "Pull request created"
  );

  return {
    prNumber: pr.number,
    prUrl: pr.html_url,
    branch: request.branch,
  };
}

// ─── PR Body Builder ────────────────────────────────────────────────────────

/**
 * Build a structured PR body from bug fix results.
 */
export function buildPRBody(
  ticketRef: string,
  summary: string,
  changedFiles: string[],
  attemptCount: number
): string {
  return [
    "## Summary",
    summary,
    "",
    "## Changed Files",
    ...changedFiles.map((f) => `- \`${f}\``),
    "",
    "## Details",
    `- Ticket: ${ticketRef}`,
    `- Auto-fix attempts: ${attemptCount}`,
    `- Pipeline: Bug Auto-Fix (Plan 09)`,
    "",
    "## Test Plan",
    "- [ ] All unit tests pass",
    "- [ ] No new lint errors",
    "- [ ] No security findings",
    "- [ ] Changed files are within agent's domain",
    "",
    "> Generated by Belva-GEN bug auto-fix pipeline",
  ].join("\n");
}
